// src/main.rs
mod http_mode;
mod logging;
mod prompts;
mod resources;
mod tools;
mod validation;
mod weather;

use rmcp::RoleServer;
use rmcp::model::{
    GetPromptRequestParams, GetPromptResponse, ListPromptsResult, ListResourceTemplatesResult,
    ListResourcesResult, PaginatedRequestParams, ReadResourceRequestParams, ReadResourceResponse,
    ServerCapabilities, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, ContentBlock},
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::Deserialize;

use tools::{CompareForecastsArgs, compare_cities};
use validation::city_name;
use weather::fetch_upstream;

#[derive(Debug, Deserialize, JsonSchema)]
struct ForecastArgs {
    /// The city to get the forecast for.
    city: String,
}

#[derive(Clone)]
struct WeatherServer {
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl WeatherServer {
    /// Creates a server with the tools generated by the tool router macro.
    fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = "Current forecast for a city")]
    /// Fetches live weather data and returns it as structured MCP content.
    async fn get_forecast(&self, Parameters(args): Parameters<ForecastArgs>) -> CallToolResult {
        let city = match city_name(&args.city) {
            Ok(city) => city,
            Err(error) => return CallToolResult::error(vec![ContentBlock::text(error)]),
        };
        logging::tool_started("get_forecast", city);

        match fetch_upstream(city).await {
            Ok(forecast) => match serde_json::to_value(forecast) {
                Ok(data) => {
                    logging::tool_succeeded("get_forecast", city);
                    CallToolResult::structured(data)
                }
                Err(error) => CallToolResult::error(vec![ContentBlock::text(format!(
                    "could not serialize forecast: {error}"
                ))]),
            },
            Err(error) => {
                logging::tool_failed("get_forecast", city, &error.to_string());
                CallToolResult::error(vec![ContentBlock::text(format!(
                    "weather lookup failed: {error}"
                ))])
            }
        }
    }

    #[tool(description = "Compare current forecasts for two cities")]
    /// Fetches and returns the current forecasts for two validated cities.
    async fn compare_forecasts(
        &self,
        Parameters(args): Parameters<CompareForecastsArgs>,
    ) -> CallToolResult {
        let (first_city, second_city) = match compare_cities(&args) {
            Ok(cities) => cities,
            Err(error) => return CallToolResult::error(vec![ContentBlock::text(error)]),
        };
        let first = match fetch_upstream(first_city).await {
            Ok(forecast) => forecast,
            Err(error) => {
                return CallToolResult::error(vec![ContentBlock::text(error.to_string())]);
            }
        };
        let second = match fetch_upstream(second_city).await {
            Ok(forecast) => forecast,
            Err(error) => {
                return CallToolResult::error(vec![ContentBlock::text(error.to_string())]);
            }
        };
        CallToolResult::structured(serde_json::json!({ "forecasts": [first, second] }))
    }
}

#[tool_handler]
impl ServerHandler for WeatherServer {
    /// Advertises the tools, resources, and prompts implemented by this server.
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .enable_prompts()
                .build(),
        )
    }

    /// Lists static resources known by the server.
    fn list_resources(
        &self,
        request: Option<PaginatedRequestParams>,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListResourcesResult, rmcp::ErrorData>> + Send
    {
        resources::list_resources(self, request, context)
    }

    /// Lists URI templates for dynamic resources.
    fn list_resource_templates(
        &self,
        request: Option<PaginatedRequestParams>,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListResourceTemplatesResult, rmcp::ErrorData>> + Send
    {
        resources::list_resource_templates(self, request, context)
    }

    /// Reads a resource by URI.
    fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ReadResourceResponse, rmcp::ErrorData>> + Send
    {
        resources::read_resource(self, request, context)
    }

    /// Lists reusable prompts exposed by the server.
    fn list_prompts(
        &self,
        request: Option<PaginatedRequestParams>,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListPromptsResult, rmcp::ErrorData>> + Send {
        prompts::list_prompts(self, request, context)
    }

    /// Expands a reusable prompt using client arguments.
    fn get_prompt(
        &self,
        request: GetPromptRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<GetPromptResponse, rmcp::ErrorData>> + Send {
        prompts::get_prompt(self, request, context)
    }
}

#[tokio::main]
/// Starts the server over stdio, or Streamable HTTP when `--http` is supplied.
async fn main() -> anyhow::Result<()> {
    if std::env::args().any(|argument| argument == "--http") {
        return http_mode::run_http().await;
    }
    let service = WeatherServer::new().serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}
